// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPX5TMAIq9j6V1wPFlJb0WhggjLvXcVbc',
    appId: '1:932656581956:web:844b66541a2b9dd62a1b11',
    messagingSenderId: '932656581956',
    projectId: 'flutter-9977c',
    authDomain: 'flutter-9977c.firebaseapp.com',
    storageBucket: 'flutter-9977c.appspot.com',
    measurementId: 'G-CTKP2FJCS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl1LODzkpXcqiVicIjjDNB6kQsFLdpq3U',
    appId: '1:932656581956:android:3155d913428ff7b12a1b11',
    messagingSenderId: '932656581956',
    projectId: 'flutter-9977c',
    storageBucket: 'flutter-9977c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHj1ZtayOIWNq2q-K-vCyN-EzZVYZBPTs',
    appId: '1:932656581956:ios:0334624beffbbd842a1b11',
    messagingSenderId: '932656581956',
    projectId: 'flutter-9977c',
    storageBucket: 'flutter-9977c.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHj1ZtayOIWNq2q-K-vCyN-EzZVYZBPTs',
    appId: '1:932656581956:ios:8ae15d5f37c2c9bc2a1b11',
    messagingSenderId: '932656581956',
    projectId: 'flutter-9977c',
    storageBucket: 'flutter-9977c.appspot.com',
    iosBundleId: 'com.example.flutterApplication3.RunnerTests',
  );
}
